In [5]:
import sys
sys.path.append("../ETL")  # o la ruta absoluta
from clima.transform_por_estacion import *
import pandas as pd

In [4]:
path = '../data/datos-estaciones/A872840.xls'
df_crudo = pd.read_excel(path)
df_crudo.head()

,Fecha,Temperatura_Abrigo_150cm,Temperatura_Abrigo_150cm_Maxima,Temperatura_Abrigo_150cm_Minima,Temperatura_Intemperie_5cm_Minima,Temperatura_Intemperie_50cm_Minima,Temperatura_Suelo_5cm_Media,Temperatura_Suelo_10cm_Media,Temperatura_Inte_5cm,Temperatura_Intemperie_150cm_Minima,...,Duracion_Follaje_Mojado,Velocidad_Viento_200cm_Media,Direccion_Viento_200cm,Velocidad_Viento_1000cm_Media,Direccion_Viento_1000cm,Velocidad_Viento_Maxima,Presion_Media,Radiacion_Global,Horas_Frio,Unidades_Frio
0,2014-11-12 00:00:00.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN
1,2014-11-13 00:00:00.0,20.07361,30.3,9.5,NaN,NaN,NaN,23.46319,NaN,NaN,...,NaN,NaN,C,NaN,C,NaN,NaN,NaN,0.0,-14.94001
2,2014-11-14 00:00:00.0,21.56181,31.3,10.9,NaN,NaN,NaN,25.29722,NaN,NaN,...,NaN,NaN,C,NaN,C,NaN,NaN,NaN,0.0,-14.27601
3,2014-11-15 00:00:00.0,20.39375,32.0,8.3,NaN,NaN,NaN,25.67361,NaN,NaN,...,NaN,NaN,C,NaN,C,NaN,NaN,NaN,0.0,-12.53301
4,2014-11-16 00:00:00.0,21.34722,31.9,9.7,NaN,NaN,NaN,26.99097,NaN,NaN,...,NaN,NaN,C,NaN,C,NaN,NaN,NaN,0.0,-15.77001

In [12]:
df_crudo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3886 entries, 0 to 3885
Data columns (total 30 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Fecha                                3886 non-null   object
 1   Temperatura_Abrigo_150cm             3672 non-null   float64
 2   Temperatura_Abrigo_150cm_Maxima      3660 non-null   float64
 3   Temperatura_Abrigo_150cm_Minima      3660 non-null   float64
 4   Temperatura_Intemperie_5cm_Minima    0 non-null      float64
 5   Temperatura_Intemperie_50cm_Minima   0 non-null      float64
 6   Temperatura_Suelo_5cm_Media          0 non-null      float64
 7   Temperatura_Suelo_10cm_Media         3671 non-null   float64
 8   Temperatura_Inte_5cm                 0 non-null      float64
 9   Temperatura_Intemperie_150cm_Minima  0 non-null      float64
 10  Humedad_Suelo                        0 non-null      float64
 11  Precipitacion_Pluviometrica          3646 non-null   float64
 12  Precipitacion_Cronologica            3641 non-null   float64
 13  Precipitacion_Maxima_30minutos       3655 non-null   float64
 14  Heliofania_Efectiva                  0 non-null      float64
 15  Heliofania_Relativa                  0 non-null      float64
 16  Tesion_Vapor_Media                   3672 non-null   float64
 17  Humedad_Media                        3672 non-null   float64
 18  Humedad_Media_8_14_20                3676 non-null   float64
 19  Rocio_Medio                          3672 non-null   float64
 20  Duracion_Follaje_Mojado              0 non-null      float64
 21  Velocidad_Viento_200cm_Media         0 non-null      float64
 22  Direccion_Viento_200cm               3886 non-null   object
 23  Velocidad_Viento_1000cm_Media        0 non-null      float64
 24  Direccion_Viento_1000cm              3886 non-null   object
 25  Velocidad_Viento_Maxima              0 non-null      float64
 26  Presion_Media                        0 non-null      float64
 27  Radiacion_Global                     0 non-null      float64
 28  Horas_Frio                           3626 non-null   float64
 29  Unidades_Frio                        3511 non-null   float64
dtypes: float64(27), object(3)
memory usage: 910.9+ KB

In [6]:
pipeline(df_crudo, path)

INFO - id_estacion inferido desde archivo: A872840
WARNING - Radiación: regresión no pudo entrenarse/aplicarse (Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by LinearRegression.). Se continúa con interpolación.
INFO - Eliminadas 3886 filas con nulos en ['radiacion_global'].

Empty DataFrame
Columns: [fecha, id_estacion, precipitacion_pluviometrica, temperatura_minima, temperatura_maxima, temperatura_media, humedad_media, rocio_medio, tesion_vapor_media, radiacion_global, heliofania_efectiva, heliofania_relativa]
Index: []

In [10]:
df_limpio

Empty DataFrame
Columns: [fecha, precipitacion_pluviometrica, temperatura_minima, temperatura_maxima, temperatura_media, humedad_media, rocio_medio, tesion_vapor_media, radiacion_global, heliofania_efectiva, heliofania_relativa]
Index: []